service: workshop-${self:custom.name}

custom:
  name: 'vho'
  email: 'vanessa.lg.ho@gmail.com'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get